import React, { useState } from 'react';
import { 
  Network, ShieldAlert, Cpu, AlertTriangle, Info, 
  MapPin, Globe, CreditCard, Layers, ArrowRight, User
} from 'lucide-react';

const NODES_DATA = [
  // Cluster A: Safe Routing Group
  { id: 'USR-2089', label: 'Liam A.', type: 'account', group: 'safe', risk: 8, cx: 160, cy: 110, details: { user: 'Liam Anderson', regDate: '2024-03-12', txCount: 142, volume: '$12,450', location: 'London, UK', extra: 'Highly trusted profile. Constant device footprint.' } },
  { id: 'USR-5561', label: 'Sarah J.', type: 'account', group: 'safe', risk: 3, cx: 120, cy: 180, details: { user: 'Sarah Jenkins', regDate: '2025-01-09', txCount: 45, volume: '$1,920', location: 'New York, US', extra: 'Clean transaction history. Standard travel behavior.' } },
  { id: 'IP-192.168.1.1', label: 'IP-192.168', type: 'ip', group: 'safe', risk: 4, cx: 200, cy: 150, details: { ipAddress: '192.168.1.1', ISP: 'BT Broadband', country: 'United Kingdom', txCount: 89, extra: 'Residential IP address. No hosting center signatures.' } },
  { id: 'DEV-MAC40', label: 'MAC40', type: 'device', group: 'safe', risk: 10, cx: 240, cy: 90, details: { deviceName: 'Apple MacBook Pro', os: 'macOS Sonoma', screen: '2560x1600', txCount: 122, extra: 'Biometric fingerprint scanner enabled. Hardware signature matches.' } },
  { id: 'DEV-IPH14', label: 'IPH14', type: 'device', group: 'safe', risk: 6, cx: 250, cy: 190, details: { deviceName: 'Apple iPhone 15 Pro', os: 'iOS 17.2', carrier: 'Verizon US', txCount: 18, extra: 'Trusted iOS application token verified.' } },

  // Cluster B: DETECTED FRAUD RING (Shared Compromised Device ID)
  { id: 'DEV-9801', label: 'DEV-9801', type: 'device', group: 'fraud', risk: 99, cx: 520, cy: 220, details: { deviceName: 'Emulated Android 11', os: 'Android OS (Rooted)', screen: '1080x1920', txCount: 12, extra: 'Device ID is generated by emulator software. Shares precise hardware canvas fingerprint across 5 unique user accounts.' } },
  
  { id: 'USR-FA67', label: 'F. Account 1', type: 'account', group: 'fraud', risk: 95, cx: 430, cy: 160, details: { user: 'Fake Acc 09A', regDate: '2026-05-20', txCount: 3, volume: '$4,200', location: 'Kiev, UA', extra: 'Registered 2 days ago. Attempting high volume transfers. Shares device DEV-9801.' } },
  { id: 'USR-FA91', label: 'F. Account 2', type: 'account', group: 'fraud', risk: 99, cx: 410, cy: 270, details: { user: 'Fake Acc 44B', regDate: '2026-05-21', txCount: 1, volume: '$8,900', location: 'Moscow, RU', extra: 'Impossible travel velocity registered. Linked directly to proxy node IP-185.22.' } },
  { id: 'USR-FA03', label: 'F. Account 3', type: 'account', group: 'fraud', risk: 88, cx: 490, cy: 320, details: { user: 'Fake Acc 11Z', regDate: '2026-05-22', txCount: 2, volume: '$1,500', location: 'Minsk, BY', extra: 'Multiple cards added in short sequence. Registered from hosting network.' } },
  { id: 'USR-FA12', label: 'F. Account 4', type: 'account', group: 'fraud', risk: 91, cx: 610, cy: 290, details: { user: 'Fake Acc 88Y', regDate: '2026-05-19', txCount: 4, volume: '$3,100', location: 'Moscow, RU', extra: 'Shares compromised emulated device DEV-9801 with 4 other active nodes.' } },
  { id: 'USR-FA88', label: 'F. Account 5', type: 'account', group: 'fraud', risk: 96, cx: 620, cy: 170, details: { user: 'Fake Acc 66X', regDate: '2026-05-20', txCount: 1, volume: '$5,000', location: 'St. Petersburg, RU', extra: 'Rapid account creation and direct conversion sequence.' } },
  
  { id: 'IP-185.22.4.9', label: 'IP-185.22', type: 'ip', group: 'fraud', risk: 94, cx: 340, cy: 210, details: { ipAddress: '185.22.4.9', ISP: 'Virtual Hosting Services', country: 'Seychelles (VPN)', txCount: 15, extra: 'Identified as a commercial proxy/VPN server exit node. Used for geographical obfuscation.' } },
  { id: 'IP-185.22.4.1', label: 'IP-185.20', type: 'ip', group: 'fraud', risk: 92, cx: 590, cy: 100, details: { ipAddress: '185.22.4.10', ISP: 'Hosting Cloud Proxy', country: 'Netherlands', txCount: 8, extra: 'Cloud hosting IP address range. High velocity API transaction pattern.' } }
];

const LINKS_DATA = [
  // Cluster A (Safe Connections)
  { source: 'USR-2089', target: 'IP-192.168.1.1', group: 'safe' },
  { source: 'USR-5561', target: 'IP-192.168.1.1', group: 'safe' },
  { source: 'DEV-MAC40', target: 'IP-192.168.1.1', group: 'safe' },
  { source: 'DEV-IPH14', target: 'IP-192.168.1.1', group: 'safe' },
  { source: 'USR-2089', target: 'DEV-MAC40', group: 'safe' },

  // Cluster B (Compromised Device Connections - FRAUD RING signature)
  { source: 'USR-FA67', target: 'DEV-9801', group: 'fraud' },
  { source: 'USR-FA91', target: 'DEV-9801', group: 'fraud' },
  { source: 'USR-FA03', target: 'DEV-9801', group: 'fraud' },
  { source: 'USR-FA12', target: 'DEV-9801', group: 'fraud' },
  { source: 'USR-FA88', target: 'DEV-9801', group: 'fraud' },

  // Proxy connections
  { source: 'USR-FA67', target: 'IP-185.22.4.9', group: 'fraud' },
  { source: 'USR-FA91', target: 'IP-185.22.4.9', group: 'fraud' },
  { source: 'USR-FA88', target: 'IP-185.22.4.1', group: 'fraud' },
  { source: 'USR-FA12', target: 'IP-185.22.4.1', group: 'fraud' }
];

export default function ThreatNetworkView() {
  const [selectedNode, setSelectedNode] = useState(NODES_DATA.find(n => n.id === 'DEV-9801'));

  const handleNodeClick = (node) => {
    setSelectedNode(node);
  };

  return (
    <div className="view-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '24px', height: '100%' }}>
      
      {/* View Description */}
      <div className="glass-panel" style={{ padding: '18px 24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <Network size={22} color="var(--cyan-accent)" style={{ filter: 'drop-shadow(0 0 5px var(--cyan-glow))' }} />
          <div>
            <h2 style={{ fontSize: '16px', fontWeight: 600, color: 'var(--text-primary)' }}>Threat Network Analysis (Link-Graph Model)</h2>
            <p style={{ fontSize: '12px', color: 'var(--text-secondary)', marginTop: '2px' }}>
              Correlating user profiles, device canvas tokens, and routing nodes to detect coordinated fraud syndicates
            </p>
          </div>
        </div>
      </div>

      <div className="threat-network-layout">
        
        {/* Left Area: Dynamic Graph Viewport */}
        <div className="glass-panel graph-panel">
          <div className="panel-header">
            <span className="panel-title">
              <Layers size={16} /> Graph Cluster Model: Multi-Device Ring
            </span>
            <span className="panel-subtitle">V2.4 Active Core Model</span>
          </div>

          <div className="graph-viewport">
            <svg className="network-svg">
              {/* Grid Background */}
              <defs>
                <pattern id="graph-grid" width="30" height="30" patternUnits="userSpaceOnUse">
                  <path d="M 30 0 L 0 0 0 30" fill="none" stroke="rgba(255,255,255,0.015)" strokeWidth="0.5" />
                </pattern>
              </defs>
              <rect width="100%" height="100%" fill="url(#graph-grid)" />

              {/* Render Network Links */}
              {LINKS_DATA.map((link, idx) => {
                const sourceNode = NODES_DATA.find(n => n.id === link.source);
                const targetNode = NODES_DATA.find(n => n.id === link.target);
                if (!sourceNode || !targetNode) return null;

                const isFraud = link.group === 'fraud';
                return (
                  <line
                    key={`link-${idx}`}
                    x1={sourceNode.cx}
                    y1={sourceNode.cy}
                    x2={targetNode.cx}
                    y2={targetNode.cy}
                    className={isFraud ? 'network-link fraud-ring-critical' : 'network-link'}
                  />
                );
              })}

              {/* Render Network Nodes */}
              {NODES_DATA.map((node) => {
                const isSelected = selectedNode && selectedNode.id === node.id;
                const isFraud = node.group === 'fraud';
                const nodeColor = node.type === 'account' ? 'account' : node.type === 'ip' ? 'ip' : 'device';

                return (
                  <g 
                    key={node.id} 
                    transform={`translate(0, 0)`}
                    onClick={() => handleNodeClick(node)}
                    className={`network-node ${isSelected ? 'selected' : ''} ${node.id === 'DEV-9801' ? 'fraud-target' : ''} ${nodeColor}`}
                  >
                    {/* Glowing outer circle for fraud nodes */}
                    {isFraud && (
                      <circle
                        cx={node.cx}
                        cy={node.cy}
                        r={node.type === 'device' ? 18 : 12}
                        fill="none"
                        stroke="var(--red-accent)"
                        strokeOpacity="0.15"
                        strokeWidth="4"
                      />
                    )}
                    {/* Node Core */}
                    <circle
                      cx={node.cx}
                      cy={node.cy}
                      r={node.type === 'device' ? 10 : node.type === 'ip' ? 7 : 7}
                      className="network-node-circle"
                    />
                    {/* Node label */}
                    <text
                      x={node.cx}
                      y={node.cy + (node.type === 'device' ? 24 : 18)}
                      className="network-node-label"
                    >
                      {node.label}
                    </text>
                  </g>
                );
              })}
            </svg>

            {/* Instruction tooltip */}
            <div className="graph-instruction">
              <Info size={12} style={{ display: 'inline', marginRight: '4px', verticalAlign: 'text-bottom' }} />
              Click any node in the model to analyze identity linkages
            </div>

            {/* Critical threat banner */}
            <div className="threat-ring-banner critical">
              <ShieldAlert size={14} />
              <span>COORDINATED ATTACK DETECTED: [DEV-9801 RING]</span>
            </div>
          </div>
        </div>

        {/* Right Area: Interactive Side Panel with Selected Node Details */}
        <div className="glass-panel details-panel">
          <div className="panel-header">
            <span className="panel-title">Node Diagnostics</span>
          </div>

          {!selectedNode ? (
            <div className="detail-card-empty">
              <Network size={36} style={{ marginBottom: '12px', opacity: 0.3 }} />
              <p>No entity selected for analysis.</p>
              <p style={{ fontSize: '11px', marginTop: '6px' }}>Select an active account, device token, or routing IP from the threat ring visualizer.</p>
            </div>
          ) : (
            <div className="detail-card-active">
              {/* Header Info */}
              <div className="detail-node-header">
                <div className={`detail-node-avatar ${selectedNode.group === 'fraud' ? 'threat' : selectedNode.type}`}>
                  {selectedNode.type === 'account' ? <User size={20} /> : selectedNode.type === 'ip' ? <Globe size={20} /> : <Layers size={20} />}
                </div>
                <div className="detail-title-info">
                  <span className="detail-id">{selectedNode.id}</span>
                  <span className="detail-type-tag">{selectedNode.type} Node ({selectedNode.group})</span>
                </div>
              </div>

              {/* Risk Gauge */}
              <div className="detail-risk-gauge">
                <div className="gauge-header">
                  <span className="gauge-label">Calculated Entity Risk</span>
                  <span className={`gauge-value ${selectedNode.risk >= 80 ? 'high' : selectedNode.risk >= 30 ? 'med' : 'low'}`}>
                    {selectedNode.risk}%
                  </span>
                </div>
                <div className="gauge-bar-track">
                  <div 
                    className={`gauge-bar-fill ${selectedNode.risk >= 80 ? 'high' : selectedNode.risk >= 30 ? 'med' : 'low'}`}
                    style={{ width: `${selectedNode.risk}%` }}
                  ></div>
                </div>
              </div>

              {/* Metadata details */}
              <div>
                <span className="detail-section-title">Telemetry Metadata</span>
                <div className="detail-meta-list">
                  {selectedNode.type === 'account' && (
                    <>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Acc Holder</span>
                        <span className="detail-meta-value">{selectedNode.details.user}</span>
                      </div>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Reg Date</span>
                        <span className="detail-meta-value">{selectedNode.details.regDate}</span>
                      </div>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Tx Count</span>
                        <span className="detail-meta-value">{selectedNode.details.txCount}</span>
                      </div>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Vol Scanned</span>
                        <span className="detail-meta-value">{selectedNode.details.volume}</span>
                      </div>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Endpoint Location</span>
                        <span className="detail-meta-value">{selectedNode.details.location}</span>
                      </div>
                    </>
                  )}

                  {selectedNode.type === 'ip' && (
                    <>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Resolved IP</span>
                        <span className="detail-meta-value">{selectedNode.details.ipAddress}</span>
                      </div>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Carrier ISP</span>
                        <span className="detail-meta-value">{selectedNode.details.ISP}</span>
                      </div>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Geographic Code</span>
                        <span className="detail-meta-value">{selectedNode.details.country}</span>
                      </div>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Correlated Nodes</span>
                        <span className="detail-meta-value">{selectedNode.details.txCount}</span>
                      </div>
                    </>
                  )}

                  {selectedNode.type === 'device' && (
                    <>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Resolved Device</span>
                        <span className="detail-meta-value">{selectedNode.details.deviceName}</span>
                      </div>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Software Platform</span>
                        <span className="detail-meta-value">{selectedNode.details.os}</span>
                      </div>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Canvas Canvas Size</span>
                        <span className="detail-meta-value">{selectedNode.details.screen}</span>
                      </div>
                      <div className="detail-meta-item">
                        <span className="detail-meta-label">Unique Linked Accs</span>
                        <span className="detail-meta-value threat-alert">
                          {selectedNode.id === 'DEV-9801' ? '5 Accounts' : '1 Account'}
                        </span>
                      </div>
                    </>
                  )}
                </div>
              </div>

              {/* Shared Threat Factor Box */}
              <div className="alert-factors-box">
                <span className="detail-section-title" style={{ color: 'var(--red-accent)' }}>
                  Threat Signature Analysis
                </span>
                <div style={{ marginTop: '8px' }}>
                  <div className="factor-item">
                    <ShieldAlert size={12} />
                    <span>{selectedNode.details.extra}</span>
                  </div>
                  {selectedNode.group === 'fraud' && (
                    <>
                      <div className="factor-item">
                        <AlertTriangle size={12} />
                        <span>High-frequency account switching linked to same token.</span>
                      </div>
                      <div className="factor-item">
                        <Cpu size={12} />
                        <span>XGBoost Signature: Device Emulator Spoofing Pattern detected.</span>
                      </div>
                    </>
                  )}
                </div>
              </div>

            </div>
          )}
        </div>

      </div>
    </div>
  );
}
